### ISSUE TITLE
No type named `bad_alloc` in namespace 'std'

### ISSUE THREAD

**Issue by DIlkhush00** [codylico/text-complex-plus#8]
While executing the `make` command, the following error shows up:

```
 error: no type named 'bad_alloc' in namespace 'std'
    } catch (std::bad_alloc const& ) {
             ~~~~~^
1 error generated.
make[2]: *** [mmaptwo-plus/CMakeFiles/mmaptwo_plus.dir/mmaptwo.cpp.o] Error 1
make[1]: *** [mmaptwo-plus/CMakeFiles/mmaptwo_plus.dir/all] Error 2
make: *** [all] Error 2
```

The problem is in this line: 
https://github.com/codylico/text-complex-plus/blob/ef75fc218eeff993957f6bbacebc6a4ef0ec75ad/mmaptwo-plus/mmaptwo.cpp#L762

And I think this can be fixed by including `<new>` header.

**Comment by codylico** [comment]
Hello, @DIlkhush00,

Thank you for the feedback. I agree that including `<new>` should solve the issue. I'll try to get the fix going by end of this week.

**Comment by codylico** [comment]
I have created branch `update-mmaptwo-library-202409`. @DIlkhush00, if you have a chance within the next week, let me know if that branch works for you.

**Comment by DIlkhush00** [comment]
@codylico, everything went smoothly aside from a few warnings.
